# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Feline Fine
email: contact@felinefine.org
description: >-
  The Feline Fine is a Sea of Thieves group that prides itself from having representation from all the game's main factions!
url: "https://felinefine.org"
github_username: Feline-Fine-Guild

head: >-
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Feline Fine</title>
      <link rel="icon" type='image/x-icon' href="assets/favicon.ico">
  </head>

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

google_analytics: ${{ secrets.analytics }}

defaults:
  - scope:
      path: "assets"
    values:
      image: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/